[build]
target-dir = "Target"

[cargo-new]
vcs = "git"

[profile.release]
opt-level = 3
codegen-units = 1
debug = false
lto = true
panic = "abort"
strip = true

[target.aarch64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+lse,+crt-static", "-Ctarget-cpu=neoverse-n1"]
linker = "./linker/cc-aarch64-linux-musl"
ar = "./linker/ar"

[target.x86_64-unknown-linux-musl]
rustflags = ["-Ctarget-feature=+crt-static"]
linker = "./linker/cc-x86_64-linux-musl"
ar = "./linker/ar"

[unstable]
build-std = ["core", "compiler_builtins", "alloc", "std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
